 
 /*------------------------------------------------------------------------
    File        : BookService
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : rainr
    Created     : Mon May 13 16:06:29 EEST 2024
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS AddBook:
    /* Business logic for adding a book */
END CLASS.

CLASS ModifyBook:
    /* Business logic for modifying a book */
END CLASS.

CLASS LendBook:
    /* Business logic for lending out a book */
END CLASS.

CLASS ReportLentBooks:
    /* Business logic for generating a report of all books lent out */
END CLASS.