
/*------------------------------------------------------------------------
    File        : BookService
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : rainr
    Created     : Mon May 13 16:16:22 EEST 2024
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

INTERFACE src.service.BookService:  
  
END INTERFACE.