
/*------------------------------------------------------------------------
    File        : BookGenre
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : rainr
    Created     : Mon May 13 15:06:08 EEST 2024
    Notes       : 
  ----------------------------------------------------------------------*/

ENUM BookGenre :  
    DEFINE ENUM History 
                Action 
                Romantic.
END ENUM.
